// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyak7XvJ-0BD3nqj9m40MP7H-Yhim_M8I',
    appId: '1:905976017867:web:ccb1df2f43f95e16da7c4e',
    messagingSenderId: '905976017867',
    projectId: 'gym-progress-26512',
    authDomain: 'gym-progress-26512.firebaseapp.com',
    storageBucket: 'gym-progress-26512.firebasestorage.app',
    measurementId: 'G-5JFC3DJWC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtIiNq4M4d8VKLTYKbCMLSobMZkP_-nA',
    appId: '1:905976017867:android:c0cb610e8837ef9eda7c4e',
    messagingSenderId: '905976017867',
    projectId: 'gym-progress-26512',
    storageBucket: 'gym-progress-26512.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvSu-yCtUncbJGK0XzMLhZKQoK9qzLsM',
    appId: '1:905976017867:ios:f271eff65e8172c0da7c4e',
    messagingSenderId: '905976017867',
    projectId: 'gym-progress-26512',
    storageBucket: 'gym-progress-26512.firebasestorage.app',
    iosBundleId: 'com.example.gymProgress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyvSu-yCtUncbJGK0XzMLhZKQoK9qzLsM',
    appId: '1:905976017867:ios:f271eff65e8172c0da7c4e',
    messagingSenderId: '905976017867',
    projectId: 'gym-progress-26512',
    storageBucket: 'gym-progress-26512.firebasestorage.app',
    iosBundleId: 'com.example.gymProgress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyak7XvJ-0BD3nqj9m40MP7H-Yhim_M8I',
    appId: '1:905976017867:web:fd2f7be3dc8d1864da7c4e',
    messagingSenderId: '905976017867',
    projectId: 'gym-progress-26512',
    authDomain: 'gym-progress-26512.firebaseapp.com',
    storageBucket: 'gym-progress-26512.firebasestorage.app',
    measurementId: 'G-BN8E9S76ZG',
  );
}
